# Generated by Django 4.2 on 2025-07-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0002_remove_applicationuser_device_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationuser",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="applicationuser",
            name="area",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Area"
            ),
        ),
        migrations.AddField(
            model_name="applicationuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="applicationuser",
            name="pin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="PIN Code"
            ),
        ),
        migrations.AddField(
            model_name="applicationuser",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State"
            ),
        ),
    ]
