# Generated by Django 4.2 on 2025-07-26 05:21

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0003_applicationuser_address_applicationuser_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationuser",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Lettres , digits and @/./+/-/ only .",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
