# Generated by Django 4.2 on 2025-07-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0005_wallet_merchantprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationuser",
            name="merchant_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stores related MerchantProfile ID.",
                null=True,
                verbose_name="Merchant ID",
            ),
        ),
    ]
