# Generated by Django 4.2 on 2025-07-27 10:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("custom_auth", "0006_applicationuser_merchant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="merchant/banner/"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Merchant Email"
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="fssai_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("others", "Others")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="merchant/logo/"),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Merchant Phone",
            ),
        ),
        migrations.AddField(
            model_name="merchantprofile",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merchants",
                to="custom_auth.category",
            ),
        ),
    ]
