# Generated by Django 4.2 on 2025-07-29 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "custom_auth",
            "0008_sitesetting_rename_updated_at_wallet_update_time_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="object_id",
        ),
        migrations.AddField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wallet",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
