# Generated by Django 4.2 on 2025-07-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voucher", "0002_voucher_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVoucherRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_delete", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("is_gift_voucher", models.BooleanField(default=False)),
                (
                    "purchase_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "purchase_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "purchase_status",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="purchased",
                        max_length=20,
                    ),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "redemption_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("redemption_notes", models.TextField(blank=True, null=True)),
                (
                    "wallet_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_redemptions",
                        to="voucher.voucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchased_at"],
                "unique_together": {("user", "voucher")},
            },
        ),
    ]
